services:
  - type: web
    name: zyork-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    port: 10000 # Match this with your PORT variable
